### ISSUE TITLE
Test execution is failing with the error in console 

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#53] opened 2017-07-27 11:40 UTC
- When running tests with recink for full e2e library there is an error with the following text
 `The Electron 1.6.11 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`
- bug is reproducing on both environments : local machine and travis ci

Please refer to attachments for more details:
<img width="556" alt="screen shot 2017-07-27 at 12 02 58" src="https://user-images.githubusercontent.com/12330493/28668628-7ad8a568-72d9-11e7-8401-82bd8a5e49d4.png">

**Comment by avozicov** [comment] 2017-07-27 12:13
Update:
It seems like execution is failed for the scripts including the following test scenario:
- when there is a click action for an url which is opened in new tab 

Will continue investigation and will come back with updates

**Comment by avozicov** [comment] 2017-08-01 18:57
Latest status:
- It seem like the root cause is not as described in the comment above
According the following log https://travis-ci.org/AdTechMedia/adtechmedia-website/jobs/259831475#L3057 Travis build has failed for random script (which does not contains any new tab navigation)

**Comment by AlexanderC** [comment] 2017-08-02 09:01
The Nighmare browser for TestCafe uses Electron as main backend, and it seems to be crashing while running in Travis (check `xvfb`).

It can be reproduces locally by adding the `DEBUG=*` flag and closing manually the opened browser window while tests running o_O

**Closed** 2017-08-04 15:26 UTC
Labels: bug
